version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
  build:
    working_directory: ~/circleci-starter
    docker:
      - image: cimg/base:2022.09
      - image: cimg/node:14.15.0 # Primary execution image
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: build
          command: |
            # Build
              echo '_____________beginning build'
              docker build -t udagram-frontend:dev1 ./udagram-frontend

              # Tagging
              echo '_____________beginning tag'
              docker tag udagram-frontend:dev1 daomtthuan/udagram-frontend:dev1

              echo 'DOCKER IMAGE LS____'
              docker image ls

      - run:
          name: after_success
          command: |
            # Login Docker
            echo '________LOGIN_______'
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

            # Pushing
            echo '_____________beginning push image'
            docker push daomtthuan/udagram-frontend:dev1
